name: CI/CD
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npx next-ver --go
      - uses: EndBug/add-and-commit@v9.0.0
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
